name: cv runner

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build-pdf:
    name: Build CV PDF
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and copy PDF
        run: |
          cd cv
          latexmk -pdflua cv.tex
          mkdir -p ../static
          cp cv.pdf ../static/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: static/cv.pdf

  commit-pdf:
    name: Commit PDF to repo
    needs: build-pdf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf
          path: static/

      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add static/cv.pdf
          git commit -m "Update cv.pdf [auto]" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}