name: cv runner

on:
  push:
    branches:
      - main
  pull_request:
  registry_package:

jobs:
  cv-runner:
    name: cv runner
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and copy PDF
        run: |
          cd cv
          latexmk -pdflua cv.tex
          cp cv.pdf ../static/

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: static/cv.pdf

      - name: Upload log (if exists)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: cv/template.log