name: cv runner

on:
  push:
    branches:
      - main
  pull_request:
  registry_package:
permissions:
  contents: write
jobs:
  cv-runner:
    name: cv runner
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and copy PDF
        run: |
          cd cv
          latexmk -pdflua cv.tex
          mkdir -p ../static
          cp cv.pdf ../static/

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: static/cv.pdf

      - name: Upload log (if exists)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: cv/template.log

      - name: Commit cv.pdf 
        uses: actions/checkout@v4
      - name: Commit cv.pdf to static/ and push 
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add static/cv.pdf
          git commit -m "Update cv.pdf [auto]" || echo "No changes to commit"
          git push
        env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}