name: cv runner

on:
  push:
    branches:
      - master
  pull_request:
  registry_package:

jobs:
  build-template:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build pdf
        run: latexmk -pdflua ./cv.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./static/cv.pdf

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: ./template.log
